### ISSUE TITLE
Does not match my bill?

### ISSUE THREAD

**Issue by BlwAvg** [cheald/srp-bill-calculator#3]
When I pull the hourly data from SRP, the amount for my plan does not match my bill. For example, I am on the ex-3 plan. When I look at my "account history" for the past 12 months ( 7/10/2017 - 6/11/2018 ) it shows I paid $1,577.02 for power. The application claims it was $938.37. Here is the output from the program:

ruby power.rb -f ###-###-###-Hourly-20170710-20180611.csv -p srp
I, [2018-06-29T20:30:26.969748 #590]  INFO -- : Computing...
Plans::SRP::EZThree             $938.37
Plans::SRP::ElectricVehicle     $1005.83
Plans::SRP::TimeOfUse           $1008.28
Plans::SRP::Basic               $1050.66
Plans::SRP::MPower              $1101.40

Is my understanding of this application off? I would assume it would match my existing cost for that period of time and calculate the cost of the others. I can provide data, just let me know.

**Comment by cheald** [comment]
It won't match the total bill, because it doesn't account for service charges ($20/mo for most plans), or city, county, and state taxes (combined is roughly an additional 7.79% of the energy charge + service charge, for me in Gilbert). It _should_ match the "Energy Charge" line item on your bill.

If you're comfortable with sharing the data, what would help the most is:

* Find your most recent SRP bill
* Find the "Service From" dates on it (upper right, just under the large total amount)
* Export the data for that period
* Run the tool on that data, and then see if the output matches the "Energy Charge" line item on your bill.

If it doesn't, I've got a calculation error somewhere. If you're comfortable sending me that data, you can email it to cheald@gmail.com along with the expected Energy Charge line item value, and I'll see if I can figure out where the issue lies.

Thank you for the bug report!

**Comment by BlwAvg** [comment]
You make total sense. Graph it and compare it to a few random bills and update provide and update.

**Comment by BlwAvg** [comment]
You are correct. Earthwise was also a contributing factor to my bill. 

TIL that I pay an average of 59% of my total bill in additional fees to the power company every month :/

**Comment by cheald** [comment]
Ouch. That stings, but at least it sounds like you've really got your power consumption figured out! :-)
